find_program(GLSLC glslc REQUIRED)
message(STATUS "Found glscl: ${GLSLC}")
set(TEST_DIR ${PROJECT_SOURCE_DIR}/tests)
execute_process(COMMAND ${GLSLC} --version OUTPUT_VARIABLE GLSCL_VERSION)

file(GLOB TEST_SUBDIRS RELATIVE ${TEST_DIR} ${TEST_DIR}/*)
foreach (SUBDIR ${TEST_SUBDIRS})
    message(STATUS "    Compiling shaders in ${SUBDIR}")
    file(GLOB_RECURSE SHADERS ${TEST_DIR}/${SUBDIR}/shaders/*.glsl)
    foreach (SHADER ${SHADERS})
        message(STATUS "        Compiling ${SHADER}")
        get_filename_component(FILENAME ${SHADER} NAME)
        get_filename_component(FILEPATH ${SHADER} DIRECTORY)
        string(REPLACE ".glsl" ".spv" SHADER_SPV ${FILENAME})
        execute_process(COMMAND ${GLSLC} ${SHADER} -o ${FILEPATH}/${SHADER_SPV})
        message(STATUS "        Compiled to ${FILEPATH}/${SHADER_SPV}")
    endforeach ()
endforeach ()
message(STATUS "Shaders compiled")
